### Importing the library

In [13]:
import numpy as np

### Creatig the input for neural network

In [14]:
input_feature = np.array([[0,0],[0,1],[1,0],[1,1]])
print(input_feature.shape)
input_feature

(4, 2)


array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

### Creating the output for neural network

In [15]:
target_output = np.array([[0,1,1,1]])
print(target_output)
target_output = target_output.reshape(4,1)
print(target_output.shape)
target_output

[[0 1 1 1]]
(4, 1)


array([[0],
       [1],
       [1],
       [1]])

### Creating the weights metric

In [16]:
weights = np.array([[0.1],[0.2]])
weights.shape

(2, 1)

### Creating bias and learning rate varibales

In [17]:
bias = 0.3
lr = 0.05

In [18]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [19]:
def sigmoid_der(x):
    return sigmoid(x) * (1-sigmoid(x))

### Constructing the neural network

In [26]:
for epoch in range(1000):
    inputs = input_feature
    
    #forward propogation
    in_o = np.dot(inputs,weights) + bias
    
    out_o = sigmoid(in_o)
    
    #back propogation
    error = out_o-target_output
    
    x = error.sum()
    print(x)
    
    derror_douto = error
    douto_dino = sigmoid_der(out_o)
    deriv = derror_douto * douto_dino
#     print(deriv.shape)
    
    inputs = input_feature.T
    deriv_final = np.dot(inputs,deriv)
    
    weights -= lr*deriv_final
#     print(weights)
    
    for i in deriv:
        bias -= lr*i
#         print(bias)

0.0018504521957897063
0.0018490904049677792
0.0018477297117596853
0.0018463701150671225
0.0018450116137940786
0.0018436542068444722
0.00184229789312422
0.001840942671540835
0.0018395885410028567
0.0018382355004200324
0.0018368835487030943
0.001835532684765398
0.0018341829075201044
0.0018328342158827615
0.0018314866087692644
0.001830140085098006
0.001828794643787643
0.0018274502837583445
0.0018261070039321953
0.0018247648032318486
0.001823423680582123
0.0018220836349078506
0.001820744665136223
0.0018194067701952504
0.0018180699490144003
0.0018167342005247639
0.001815399523657557
0.0018140659173465495
0.0018127333805268014
0.0018114019121335256
0.0018100715111040583
0.0018087421763770262
0.0018074139068917638
0.001806086701589521
0.0018047605594125743
0.0018034354793039498
0.0018021114602091715
0.0018007885010740965
0.0017994666008458171
0.0017981457584727856
0.001796825972905633
0.001795507243094574
0.00179418956799271
0.0017928729465531978
0.001791557377731276
0.0017902428604829462
0.0

0.000963217750053813
0.000962521899611879
0.0009618265291197053
0.0009611316381729212
0.0009604372263676136
0.0009597432933007993
0.0009590498385682183
0.0009583568617680949
0.0009576643624978898
0.000956972340355966
0.0009562807949402008
0.0009555897258501783
0.0009548991326850664
0.0009542090150444632
0.0009535193725286606
0.0009528302047380061
0.0009521415112735271
0.0009514532917371532
0.0009507655457298148
0.0009500782728539131
0.0009493914727126268
0.0009487051449080935
0.00094801928904438
0.0009473339047248036
0.000946648991553431
0.0009459645491355362
0.0009452805770755468
0.000944597074978612
0.0009439140424516851
0.0009432314790996377
0.0009425493845296312
0.000941867758348397
0.0009411866001638597
0.0009405059095833335
0.000939825686214979
0.0009391459296674148
0.000938466639549676
0.000937787815470964
0.0009371094570411465
0.00093643156387066
0.0009357541355693583
0.0009350771717483303
0.0009344006720193171
0.0009337246359937407
0.0009330490632835919
0.0009323739535013614
0

In [27]:
print(weights)

[[5.59603679]
 [5.59727208]]


In [28]:
print(bias)

[-2.42329258]


In [29]:
#predict

single_point = np.array([1,0])
result1 = np.dot(single_point,weights) + bias
result2 = sigmoid(result1)
print(result2)

[0.95979561]


In [32]:
single_point = np.array([0,0])
result1 = np.dot(single_point,weights) + bias
result2 = sigmoid(result1)
print(result2)

[0.08141368]
